name: CI

on: [push, workflow_dispatch]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Download Remote-RTC
      run: curl -L -o Remote-RTC.zip https://github.com/DigitalSerpant/Remote-RTC/releases/download/1.0.1/Remote.RTC.1.0.1.zip
    
    - name: Extract Remote-RTC
      run: Expand-Archive Remote-RTC.zip
    
    - name: Ngrok Auth
      run: .\ngrok\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}

    - name: Enable TS
      run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
    
    - name: Enable Firewall Rule
      run: Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
    
    - name: Enable User Auth
      run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -Name "UserAuthentication" -Value 1
    
    - name: Set Local User Password
      run: Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText $Env:ADMIN_PASSWORD -Force)
      env:
        ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}

    - name: Create Tunnel
      run: .\ngrok\ngrok.exe tcp 3389

    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install WebRTC
      run: .\reemo.setup.x64.exe /quiet /norestart

    - name: Run Tests
      run: npm test
